version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing system dependencies..."
      - apt update && apt install -y unzip curl git nginx mysql-client php8.3 php8.3-cli php8.3-fpm php8.3-redis php8.3-gd php8.3-readline php8.3-mysql php8.3-xml php8.3-mbstring php8.3-curl php8.3-intl php8.3-zip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo "Setting up Laravel environment..."
      - composer install --no-dev --prefer-dist --optimize-autoloader
      - php artisan key:generate
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan migrate --force

  build:
    commands:
      - echo "Configuring Permission"
      - chmod -R 775 storage bootstrap/cache
      - chown -R www-data:www-data .
      - echo "Creating artifact..."
      - zip -r ../laravel-app.zip .

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - ../laravel-app.zip
  discard-paths: yes
  name: laravel-app-${CODEBUILD_BUILD_NUMBER}

